# arxivの学問領域の指定
subject: 'cat:cs.* OR eess.AS'

# 検索キーワード
keywords:
        sound: 1
        audio: 1
        anomaly detection: 3
        reduction: 3
        dcase: 3
        anomaly: 2
        anomalies: 2
        imbalance: 2
        unbalance: 2
        sound feature: 3
        audio feature: 3
        noise removal: 2
        mfcc: 3
        ivector: 1
        spectrogram: 3
        outlier detection: 1
        koizumi: 3
# 通知の閾値
score_threshold: 0
